version: "3.9"

services:
  web:
    build: ./pokedex
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./pokedex:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=pokedex_db
      - POSTGRES_USER=ash
      - POSTGRES_PASSWORD=thisismypokedex
volumes:
  postgres_data:
